
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypkefyzvhfhpnsjxzoma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwa2VmeXp2aGZocG5zanh6b21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODAwNjQsImV4cCI6MjA2NDk1NjA2NH0.CMZRvUBAPuFpgG7q7AvzyNILfpr5TO7aabG3baIQcA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
